Invite link khong hop ly
ngodat0103/se347 pull request #103
Opened 2024-12-27 03:36 UTC by nguyenthiyenly0407

Invite link khong hop ly

2024-12-27 03:50 UTC, ngodat0103 requested changes
Chỗ invite link vẫn chưa generate đúng
![image](https://github.com/user-attachments/assets/cd88859f-a4e5-4c7b-bd5d-6b24b9fb8bf1)

2024-12-27 03:50 UTC, ngodat0103 requested changes
Chỗ invite link vẫn chưa generate đúng
![image](https://github.com/user-attachments/assets/cd88859f-a4e5-4c7b-bd5d-6b24b9fb8bf1)

2024-12-27 03:51 UTC, nguyenthiyenly0407 commented
ok

2024-12-29 10:32 UTC, SuperCoolGuy855 commented
@nguyenthiyenly0407 Hello? Có làm gì chưa vậy?

2024-12-29 11:45 UTC, closed without merging