Login register page addlogic v2
ngodat0103/se347 pull request #13
Opened 2024-11-18 16:40 UTC by ngodat0103

2024-11-18 16:47 UTC, ngodat0103 reviewed
LGTM!

2024-11-19 09:27 UTC, SuperCoolGuy855 requested changes
Login ui kêu đăng nhập bằng email, mà backend lại sử dụng username.

Với lại, nếu đăng nhập sai 1 lần, thì sẽ ko được đăng nhập nữa.

2024-11-19 09:54 UTC, SuperCoolGuy855 approved these changes

2024-11-19 17:59 UTC, ngodat0103 commented
> Login UI kêu đăng nhập bằng email, mà backend lại sử dụng username. Mà UI là ép validate email nên cũng ko thể đăng nhập bằng username.
> 
> Khi UI validate lạ, nếu input không có @ thì lại không báo lỗi.

Đã sửa Request Body của auth/login, yêu cầu email và password
![image](https://github.com/user-attachments/assets/254503fb-33e3-4c43-9b62-da1fd9b036ae)

2024-11-19 18:00 UTC, ngodat0103 commented
login page: Tạm thời hardcode đến môi trường Dev của backed, Test ok
![image](https://github.com/user-attachments/assets/dc80b5a3-d34e-4074-a167-0c0a9906f39c)

2024-11-19 18:11 UTC, ngodat0103 reviewed
LGTM!

2024-11-21 07:06 UTC, SuperCoolGuy855 commented
Sao chưa đăng kí mà đã kêu có tài khoản rồi?
![image](https://github.com/user-attachments/assets/d391f1e1-7e50-493f-a9c9-b059c911c194)

Email validation vẫn còn dở, hình như ko đồng nhất với backend. Với lại nếu client-side validation bị lỗi thì báo lỗi cho user biết.

Đăng nhập thành công thì lại bị response 2 lần, ko biết sẽ có bị gì ko
![image](https://github.com/user-attachments/assets/dd8f6eed-ceb8-48e5-8ff7-f0ce978ecc3b)

2024-11-21 07:07 UTC, SuperCoolGuy855 approved these changes

2024-11-21 07:22 UTC, ngodat0103 commented
@VietDucc  chắc tạo Issue nhắc fix lại chỗ validation bên Web
Tính năng báo lỗi sao này mới thêm

2024-11-21 07:35 UTC, VietDucc commented
> Sao chưa đăng kí mà đã kêu có tài khoản rồi?
> 
> ![image](https://github.com/user-attachments/assets/d391f1e1-7e50-493f-a9c9-b059c911c194)
> 
> 
> 
> Email validation vẫn còn dở, hình như ko đồng nhất với backend. Với lại nếu client-side validation bị lỗi thì báo lỗi cho user biết.
> 
> 
> 
> Đăng nhập sai cũng nên báo lỗi cho user biết.
> 
> 
> 
> Đăng nhập thành công thì lại bị response 2 lần, ko biết sẽ có bị gì ko
> 
> ![image](https://github.com/user-attachments/assets/dd8f6eed-ceb8-48e5-8ff7-f0ce978ecc3b)
> 
> 
> 
> Mà tạm thời chấp nhận đc.

fix lại hồi trưa rồi nhé mà chưa push

2024-11-21 07:36 UTC, VietDucc commented
> @VietDucc  chắc tạo Issue nhắc fix lại chỗ validation bên Web
> 
> Tính năng báo lỗi sao này mới thêm

thông báo lỗi nó hiện màu đỏ ở dưới mỗi textbox đó hay thêm gì

2024-11-21 07:38 UTC, ngodat0103 commented
> > @VietDucc  chắc tạo Issue nhắc fix lại chỗ validation bên Web
> > Tính năng báo lỗi sao này mới thêm
> 
> thông báo lỗi nó hiện màu đỏ ở dưới mỗi textbox đó hay thêm gì

đr

2024-11-21 07:39 UTC, ngodat0103 commented
Nhận status code 401 từ backend thì thông báo username hoặc password bị sai

2024-11-21 07:40 UTC, SuperCoolGuy855 commented
> > @VietDucc  chắc tạo Issue nhắc fix lại chỗ validation bên Web
> > Tính năng báo lỗi sao này mới thêm
> 
> thông báo lỗi nó hiện màu đỏ ở dưới mỗi textbox đó hay thêm gì

Thì thấy chỉ có báo lỗi khi server-side validation bị lỗi thôi. Còn client-side validation thì thấy ko báo lỗi, chỉ có focus vào field bị lỗi thôi.

2024-11-21 07:55 UTC, VietDucc reviewed
LGTM!

2024-11-21 08:08 UTC, VietDucc approved these changes
Good job on this! Everything looks clean and works as expected

2024-11-21 08:08 UTC, merged