vietduc(signup): Change text, redirect to login
ngodat0103/se347 pull request #27
Opened 2024-11-26 05:08 UTC by VietDucc

2024-11-27 15:47 UTC, SuperCoolGuy855 requested changes
![image](https://github.com/user-attachments/assets/a703bcf0-e5f4-427d-b3db-82cb97c977af)

1. Đừng ghi là Jira account, chỉ nên ghi là "Already have an account? Log in!"
2. Làm cho nó đồng bộ với login chứ, sao lại nguyên cái dòng chữ đó là hyperlink hết vậy. Chỉ dòng chữ "Log in" thôi. Với lại đặt dấu cách cho đúng.
3. Redirect từ sign up sang login còn bị sai. Nếu email đã tồn tại và backend báo lỗi, thì đáng lẽ phải báo lỗi cho user vaf ko redirect. Còn này lại báo là thành công mà redirect đi nữa, mặc dù không tạo thành công.

2024-12-08 14:51 UTC, ngodat0103 commented
![image](https://github.com/user-attachments/assets/fb801f2d-1382-448c-9469-4f3985f02220)

Lỗi login fetch nhầm api endpoint

2024-12-08 14:52 UTC, ngodat0103 requested changes

2024-12-08 14:52 UTC, ngodat0103 commented on frontend/jira-clone/next.config.ts
Setting này làm gì

2024-12-08 14:54 UTC, VietDucc commented on frontend/jira-clone/next.config.ts
cho phép lấy ảnh từ nguồn đó

2024-12-08 15:07 UTC, ngodat0103 commented on frontend/jira-clone/next.config.ts
này là do bên phía frontend security phải chỉ định trusted source để lấy ảnh à

2024-12-08 15:28 UTC, VietDucc commented on frontend/jira-clone/next.config.ts
ừa nextjs nó bắt

2024-12-08 16:18 UTC, ngodat0103 commented
Workspace backend thay đổi schema, chỉnh lại bên frontend
![image](https://github.com/user-attachments/assets/cf91207f-c36d-4f8c-bd57-f98f1ef19fdf)

2024-12-08 17:14 UTC, ngodat0103 commented
Thiếu handle Exception trong trường hợp tạo cố tình tạo trùng
![image](https://github.com/user-attachments/assets/f06104ad-7f0f-4173-989d-9c62214d12d5)

2024-12-08 17:25 UTC, ngodat0103 commented
![image](https://github.com/user-attachments/assets/32c1ab74-c56f-443a-9fc0-ee5c4e49ca24)
Web nên redirect về trang login khi token không tồn tại hoặc invalid

2024-12-08 18:03 UTC, ngodat0103 commented
Nên Refresh lại trang khi vừa tạo workspace
![image](https://github.com/user-attachments/assets/6d450e90-fcf7-4130-a70f-40a5f37d6c7a)

2024-12-08 18:23 UTC, ngodat0103 commented
Thêm tính năng Auto login
Khi người dùng vô web, check cookie có token, nếu code thì redirect thằng vô dashboard

2024-12-10 01:24 UTC, ngodat0103 approved these changes
LGTM!

2024-12-10 07:33 UTC, SuperCoolGuy855 approved these changes

2024-12-10 07:34 UTC, merged