[Frontend-Login] Thêm thông báo lỗi khi đăng ký tài khoản
ngodat0103/se347 pull request #57
Opened 2024-12-16 10:06 UTC by ngocdiemm

fix loi thong bao tai khoan chua dang ki

2024-12-16 11:01 UTC, ngodat0103 requested changes

2024-12-16 11:01 UTC, ngodat0103 commented on src/services/user_api.ts
Sao comment hết đống code cũ vậy

2024-12-16 15:46 UTC, SuperCoolGuy855 approved these changes

2024-12-18 10:26 UTC, ngodat0103 approved these changes

2024-12-18 10:26 UTC, merged