[Fronend]: Tạo table load các task
ngodat0103/se347 pull request #79
Opened 2024-12-22 10:29 UTC by ngodat0103

![image](https://github.com/user-attachments/assets/d3940805-ea09-467b-b722-20e1b804cfcb)

2024-12-22 10:30 UTC, ngodat0103 commented
![image](https://github.com/user-attachments/assets/d1febb07-565e-4463-bdcd-73498814f131)
load date bị conflic time, sẽ tạo issue fix sau

2024-12-22 17:23 UTC, VietDucc approved these changes
good joob Minh Dat

2024-12-22 18:55 UTC, SuperCoolGuy855 commented
T ko chọn due date được, nó ko hiện thị ngày lên để chọn, mà ko chọn due date thì ko tạo task đc. Mà chuyển sang trình duyệt khác thì lại được. Ko hiểu sao.

2024-12-22 19:00 UTC, SuperCoolGuy855 requested changes
Khi tạo task, task lại ko hiện thị đúng trong project đc chọn.

https://github.com/user-attachments/assets/bebc91e0-b590-4721-bf3a-77573c560919

2024-12-23 03:49 UTC, ngodat0103 commented
> Khi tạo task, task lại ko hiện thị đúng trong project đc chọn.
> 
>  2024-12-23.01-56-13.mp4
Fix

https://github.com/user-attachments/assets/a85f09a4-2f5c-4862-ad86-e7d391320e36

2024-12-23 05:42 UTC, SuperCoolGuy855 approved these changes

2024-12-23 05:42 UTC, merged

2024-12-25 05:10 UTC, VietDucc commented
![image](https://github.com/user-attachments/assets/67a85c38-c13b-4d4b-8f65-02a90e8794b7)
đúng ý chưa

2024-12-25 05:11 UTC, ngodat0103 commented
the F, sao comment vào issue đã close