vietduc: set role, remove members
ngodat0103/se347 pull request #80
Opened 2024-12-22 17:22 UTC by VietDucc

2024-12-22 19:19 UTC, SuperCoolGuy855 commented
![image](https://github.com/user-attachments/assets/e0ec2ee4-d314-40da-9b55-ef16d0a6dcb5)

Sao lại ghi là "Set as Administrator" mà ấn thì lại set role thành OWNER?

2024-12-22 19:19 UTC, SuperCoolGuy855 approved these changes

2024-12-23 04:07 UTC, ngodat0103 requested changes
Xử lí confict

2024-12-23 07:31 UTC, VietDucc commented
cứ merge đi minh, cái đó fix sau cũng được đúng là admin á

2024-12-23 07:32 UTC, ngodat0103 approved these changes

2024-12-23 07:33 UTC, merged